MDScreen:
    md_bg_color: app.theme_cls.bg_normal

    Label:
        text: 'Username:'
        pos_hint: {"center_x": .2, "center_y": .8}
        font_size: '20sp'
    MDTextField:
        id: input_field
        hint_text: "Usuário"
        mode: "rectangle"
        pos_hint: {"center_x": .27, "center_y": .73}
        size_hint_x: None
        width: "175dp"
        font_size: '12sp'
    Label:
        text: 'Email:'
        pos_hint: {"center_x": .65, "center_y": .8}
        font_size: '20sp'

    MDTextField:
        id: input_field
        hint_text: "Email"
        mode: "rectangle"
        pos_hint: {"center_x": .70, "center_y": .73}
        size_hint_x: None
        width: "200dp"
        font_size: '12sp'
    Label:
        text: 'Senha:'
        pos_hint: {"center_x": .18, "center_y": .60}
        font_size: '20sp'
    MDTextField:
        id: input_field
        hint_text: "Senha"
        mode: "rectangle"
        pos_hint: {"center_x": .27, "center_y": .53}
        size_hint_x: None
        width: "175dp"
        font_size: '12sp'
    Label:
        text: 'Confirmar:'
        pos_hint: {"center_x": .65, "center_y": .60}
        font_size: '20sp'
    MDTextField:
        id: input_field
        hint_text: "Confirmar"
        mode: "rectangle"
        pos_hint: {"center_x": .68, "center_y": .53}
        size_hint_x: None
        width: "175dp"
        font_size: '12sp'