CREATE DATABASE IF NOT EXISTS igreja
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE igreja;

CREATE TABLE IF NOT EXISTS obreiros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  departamentos VARCHAR(255) NOT NULL,
  dias_nao_pode TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
